kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: elasticsearch
  namespace: platform
spec:
  rules:
  - host: elasticsearch.dev
    http:
      paths:
      - path: /
        backend:
          serviceName: elasticsearch
          servicePort: 9200

---

kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: platform
spec:
  selector:
    app: elasticsearch
  ports:
  - name: http
    port: 9200
    protocol: TCP
  - name: transport
    port: 9300
    protocol: TCP
  clusterIP: None

---

kind: PetSet
apiVersion: apps/v1alpha1
metadata:
  name: elasticsearch
  namespace: platform
spec:
  serviceName: "elasticsearch"
  replicas: 1
  template:
    metadata:
      namespace: platform
      name: elasticsearch
      labels:
        app: elasticsearch
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
        pod.alpha.kubernetes.io/init-containers: '[
          {
            "name": "sysctl",
            "image": "busybox",
            "command": ["sysctl", "-w", "vm.max_map_count=262144"],
            "securityContext": {
              "privileged": true
            }
          }
        ]'
    spec:
      containers:
      - name: elasticsearch
        securityContext:
          privileged: true
        image: quay.io/pires/docker-elasticsearch-kubernetes:5.0.1_1
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        env:
        - name: "ES_JAVA_OPTS"
          value: "-Xms1024m -Xmx1024m"
        resources:
          requests:
            memory: 1Gi
          limits:
            memory: 2Gi
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
        - emptyDir:
            medium: ""
          name: "storage"
