kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: prometheus
  namespace: platform
spec:
  rules:
  - host: prometheus.dev
    http:
      paths:
      - path: /
        backend:
          serviceName: prometheus
          servicePort: 9090

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: prometheus
  name: prometheus
  namespace: platform
spec:
  selector:
    app: prometheus
  ports:
  - name: prometheus
    protocol: TCP
    port: 9090
  clusterIP: None

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
  namespace: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      name: prometheus
      namespace: platform
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: quay.io/prometheus/prometheus:v1.1.3
        args:
          - '-storage.local.retention=6h'
          - '-storage.local.memory-chunks=500000'
          - '-config.file=/etc/prometheus/prometheus.yml'
        ports:
        - name: web
          containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
      volumes:
      - name: config-volume
        configMap:
          name: prometheus
